[package]
name = "demo-reducer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlsync-reducer = { path = "../../lib/sqlsync-reducer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
